### PR TITLE
Get twiglet and db

### PR DESCRIPTION
**Pull request by moon-tea**
Resolved most of the todos.

### CODE REVIEW

**Comment by jeffbergman** [comment]
You have a commit called replacing trailing commas, yet there are a lot of places where there seems to be no trailing comma. I really like the trailing comma, and I don't agree to removing it.
How did that pass linting? Did you change linting rules or was that rule never there?

**Comment by moon-tea** [comment]
> 1. You have a commit called replacing trailing commas, yet there are a lot of places where there seems to be no trailing comma. I really like the trailing comma, and I don't agree to removing it.
> 2. How did that pass linting? Did you change linting rules or was that rule never there?

1. I will fix those, I thought it would be fixed automatically.
2. The rule is not enforced in the eslint file, I can add it.

**Comment by moon-tea** [comment]
> > 1. You have a commit called replacing trailing commas, yet there are a lot of places where there seems to be no trailing comma. I really like the trailing comma, and I don't agree to removing it.
> > 2. How did that pass linting? Did you change linting rules or was that rule never there?
> 
> 1. I will fix those, I thought it would be fixed automatically. I personally really like the trailing comma as well.
> 2. The rule is not enforced in the eslint file, I can add it.

Okay, the rule is now enforced and it changed a lot of files. We now have the trailing comma everywhere it can be.

**Comment by lizziesz** [comment]
I don't necessarily agree with changing linting rules as part of this branch (although I prefer the trailing commas too, and seems like it must not have been consistently enforced?) Since we all prefer trailing commas (and we're the current dev team on Twig) I think this change is okay, but we should avoid changing any more linting rules as part of this PR and focus on the task at hand, which is updating all the packages and making sure tests pass.

**Comment by jeffbergman** [comment]
@lizziesz I agree no further linting rule changes. When I initially reviewed the pr, I only saw places where there had been a trailing comma that was removed in the new code - so I wanted them put back. I couldn't see places where a trailing comma had not existed previously, if there were any, because they weren't changes. So I don't know whether any inconsistency had existed before.

**Pull request merged**
