### PR TITLE
Dao attempt 2

### PR DESCRIPTION
**Pull request by BenAychh**
Attempt number 2 at trying to abstract out the couch stuff in anticipation of dynamo.  Let's go over it next week sometime. We are presenting this stuff on the 14th to the wider buildit organization so I am not merging any changes in before wednesday anyway - even if i am fairly confident about my tests.

### CODE REVIEW

**Comment by mathomas** [comment]
Based on looking at the first cut, I think before introducing the Dynamo implementation (or immediately after you copy/paste the Couch one over to it), we'll want to analyze how DRY the resulting code will be.  My guess is there will be a lot of duplication, and we'll need to figure out how to avoid that.  Let's hope it doesn't become a "jerk Ben around" proposition.

**Comment by aochsner** [comment]
ok to test

**Comment by aochsner** [comment]
test this please

**Comment by aochsner** [comment]
test this please

**Comment by aochsner** [comment]
test this please

**Comment by aochsner** [comment]
closing the PR until we can pick it back up

**Comment by aochsner** [comment]
testing git PR building

**Pull request closed without merging**
